name = "Curves"
uuid = "9bed79ab-e35b-4b7a-8527-918872a9571e"
authors = ["Benjamin Lungwitz <benj.lung@googlemail.com>"]
version = "0.2.8"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Interpolations = "0.13"
julia = "1.2"
