name = "Curves"
uuid = "9bed79ab-e35b-4b7a-8527-918872a9571e"
authors = ["Benjamin Lungwitz <benj.lung@googlemail.com>"]
version = "0.2.1"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
Interpolations = "0.12"
julia = "1.2"
